### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by ZaiKL** [Johnserf-Seed/TikTokDownload#653]
**描述出现的错误**
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\kaiko\\Desktop\\zaIKL\\GITHUB\\TikTokDownload2024\\Download\\douyin\\post\\陈默\\2023-11-13 21-57-12_我是一个任性的人_因为执意要记录生活_所以一直这么拍着_我相信我们一定可以在属于自己的世界里_闪着自己的光__如果哪天我们能再相遇_一定是因为我们成了更好的自己__最后_祝你早安午安晚安__#遗憾_#我只能离开\\2023-11-13 21-57-12_我是一个任性的人_因为执意要记录生活_所以一直这么拍着_我相信我们 一定可以在属于自己的世界里_闪着自己的光__如果哪天我们能再相遇_一定是因为我们成了更好的自己__最后_祝你早安午安晚安__#遗憾_#我只能离开_music.tmp'
**bug复现**

复现这次行为的步骤：
python TikTokTool.py -u https://www.douyin.com/user/MS4wLjABAAAA4cwE4HS2RHt7N8Qc9CNC9_92cOVe1TO1DPi6wYEQ6Dw

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![图片](https://github.com/Johnserf-Seed/TikTokDownload/assets/86660941/3b2d5cd2-324e-45ed-97c5-39b904cc8aca)
![图片](https://github.com/Johnserf-Seed/TikTokDownload/assets/86660941/7b9d6a32-be40-4754-859e-6ab01fbbef82)

**桌面（请填写以下信息）：**
-操作系统：[windows11 64bit]
-vpn代理：[关闭]
-项目版本：[1.5.0.0]
-py版本：[3.12.1]

**附文**
在此处添加有关此问题的其他备注。

**Comment by ZaiKL** [comment]
![图片](https://github.com/Johnserf-Seed/TikTokDownload/assets/86660941/e253dbb0-747b-40b4-aa47-da24feb5f2ce)
短文件没问题 就是长文件 但是也没有超过255字节

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/issues/661
和该issue相同，均非文件名长度问题，需要进一步测试。我本地测试是可以正常保存的。

**Comment by snowman** [comment]
```yaml
douyin:
  cookie: ...
  headers:
    Referer: ...
    User-Agent: ...
  interval: all
  languages: zh_CN
  mode: ...
  naming: '{create}'
  url: https://v.douyin.com/iMKuQdRh/
```

改一下 `naming`
