### ISSUE TITLE
分享一下我的成功使用经过（仅用4步操作），算是给刚入门或者下载失败的人一个参考

### ISSUE THREAD

**Issue by wangnan789** [Johnserf-Seed/TikTokDownload#683]
**桌面（请填写以下信息）：**
-操作系统：[linux]
-vpn代理：[关闭]
-项目版本：[1.5.0.0]
-py版本：[3.11.1]
-下载平台：douyin.com

第 1 步
```
python3 -m venv py-env
source ./py-env/bin/activate
```
#说明：在当前目录[**创建PY虚拟环境**](https://docs.python.org/zh-cn/3/library/venv.html)，

第 2 步
`pip3 install f2`
#说明：安装f2

第 3 步
修改配置 ./py-env/lib/python3.11/site-packages/f2/conf/app.yaml
```
douyin:
  cookie: 
  cover: false
  desc: no
  folderize: false
  interval: all
  languages: zh_CN
  max_connections: 5
  max_counts: 0
  max_retries: 4
  max_tasks: 6
  mode: post
  music: false
  naming: '{create}_{aweme_id}'
  page_counts: 20
  path: ./Download
  timeout: 6
```
#说明：不要乱加引号，也不要使用“null” , 所有的冒号: 后面必须有一个空格。查看相关选项解释 `f2 dy -h`

第 4 步
使用浏览器**登录**抖音，然后**关闭**。命令行执行以下命令。支持的浏览器：chrome、firefox、edge、opera
```
f2 dy --auto-cookie firefox
```
#说明：这会将cookie值自动写到配置里，千万**不要**去手工复制，格式不对将无法下载。
#dy 表示抖音平台，查看其他平台 `f2 -h`

第 5 步
开始下载
`f2  dy  -u https://www.douyin.com/user/MS4wLjABAAAAXXXXXXXXXXXXXXXXXXXXXXXX`
#说明：下载抖音用户发布的作品。在第 3 步中“mode: post”是指用户发布的作品。
#“https://” 这个不能少
#重启电脑或命令行，只执行第 1 步 ，第 5 步

完。
